name = Sitemap
description = Page to display sitemap menu block at full width
preview = preview.png
template = sitemap


; ========================================
; Regions
; ========================================
regions[header_first] = Header First
regions[header_second] = Header Second
regions[header_third] = Header Third
regions[content] = Content
regions[footer_first] = Footer First
regions[footer_second] = Footer Second

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/sitemap/sitemap.layout.css
stylesheets[all][] = css/layouts/sitemap/sitemap.layout.no-query.css

; ========================================
; Scripts
; ========================================
scripts[] = libraries/underscore/underscore-min.js
scripts[] = js/sitemap.js