name = Longscroll
description = Longscroll page
preview = preview.png
template = longscroll


; ========================================
; Regions
; ========================================
regions[header_first] = Header First
regions[header_second] = Header Second
regions[header_third] = Header Third
regions[content_header] = Content Header
regions[above_content] = Above Content
regions[content] = Content
regions[below_content] = Below Content
regions[content_footer] = Content Footer
regions[footer_first] = Footer First
regions[footer_second] = Footer Second

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/longscroll/longscroll.layout.css
stylesheets[all][] = css/layouts/longscroll/longscroll.layout.no-query.css

; ========================================
; Scripts
; ========================================
scripts[] = libraries/waypoints/waypoints.min.js
scripts[] = js/longscroll.js