name = Two Column Layout
description = Two Columns for Landing Pages
preview = preview.png
template = twocolumn


; ========================================
; Regions
; ========================================
regions[header_first] = Header First
regions[header_second] = Header Second
regions[header_third] = Header Third
regions[content_header] = Content Header
regions[content_left] = Content Left
regions[content_right] = Content Right
regions[content_footer] = Content Footer
regions[footer_first] = Footer First
regions[footer_second] = Footer Second

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/twocolumn/twocolumn.layout.css
stylesheets[all][] = css/layouts/twocolumn/twocolumn.layout.no-query.css