name = Longscroll v2
description = Longscroll page v2
preview = preview.png
template = longscroll_v2


; ========================================
; Regions
; ========================================
regions[header_first] = Header First
regions[header_second] = Header Second
regions[header_third] = Header Third
regions[content_header] = Content Header
regions[above_content] = Above Content
regions[content] = Content
regions[below_content] = Below Content
regions[content_footer] = Content Footer
regions[footer_first] = Footer First
regions[footer_second] = Footer Second

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/longscroll_v2/longscroll_v2.layout.css
stylesheets[all][] = css/layouts/longscroll_v2/longscroll_v2.layout.no-query.css

; ========================================
; Scripts
; ========================================
scripts[] = libraries/waypoints/waypoints.min.js
scripts[] = js/longscroll_v2.js