name = Peeler
description = Each section "peels" to reveal the next
preview = preview.png
template = peeler


; ========================================
; Regions
; ========================================
regions[header_first] = Header First
regions[header_second] = Header Second
regions[header_third] = Header Third
regions[content_header] = Content Header
regions[above_content] = Above Content
regions[content] = Content
regions[below_content] = Below Content
regions[content_footer] = Content Footer
regions[footer_first] = Footer First
regions[footer_second] = Footer Second

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/peeler/peeler.layout.css
stylesheets[all][] = css/layouts/peeler/peeler.layout.no-query.css
; stylesheets[all][] = libraries/peeler/css/peeler.css

; ========================================
; Scripts
; ========================================
