name = Default Inner
description = Default interior page
preview = preview.png
template = default_inner


; ========================================
; Regions
; ========================================
regions[header_first] = Header First
regions[header_second] = Header Second
regions[header_third] = Header Third
regions[content_header] = Content Header
regions[nav_sidebar] = Navigation Sidebar
regions[featured] = Featured Content
regions[above_content] = Above Content
regions[content] = Content
regions[below_content] = Below Content
regions[promo_sidebar] = Promo Sidebar
regions[content_footer] = Content Footer
regions[footer_first] = Footer First
regions[footer_second] = Footer Second

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/default_inner/default_inner.layout.css
stylesheets[all][] = css/layouts/default_inner/default_inner.layout.no-query.css